# Generated by Django 4.1.4 on 2023-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='imgfolder')),
                ('CategoryDescrition', models.CharField(max_length=50)),
            ],
        ),
    ]
