# Generated by Django 4.1.4 on 2023-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=20)),
                ('ProductName', models.CharField(max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='imgfolder')),
                ('ProductDescrition', models.CharField(max_length=50)),
                ('Productprice', models.FloatField()),
            ],
        ),
    ]
