# Generated by Django 4.1.4 on 2023-09-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_producttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='Productprice',
            new_name='ProductPrice',
        ),
    ]
