# Generated by Django 4.1.4 on 2023-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logintable',
        ),
        migrations.RemoveField(
            model_name='registrationtable',
            name='City',
        ),
        migrations.RemoveField(
            model_name='registrationtable',
            name='District',
        ),
        migrations.RemoveField(
            model_name='registrationtable',
            name='Name',
        ),
        migrations.AddField(
            model_name='registrationtable',
            name='Password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registrationtable',
            name='UserName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
